Add Store Update and Delete APIs
JoshRyu/logistics pull request #12
Opened 2023-12-05 13:42 UTC by ZinnaChoi

Hello @JoshRyu~

I've implemented store delete and update APIs!
I've also simplified the complex service logic.

Now, I've successfully addressed this [issue](https://github.com/JoshRyu/logistics/issues/7).
Please take a look and feel free to provide feedback!

Thank you.

2023-12-05 13:54 UTC, JoshRyu commented on backend/src/main/java/com/madeg/logistics/service/CategoryService.java
> +        patchInput.getParentCategoryCode()
you've declared parentCategoryCode in line 89, what about reusing it?

2023-12-05 13:56 UTC, JoshRyu commented on backend/src/main/java/com/madeg/logistics/service/StoreService.java
> +      isUpdated = true;
seems isUpdated = true; statement is repeated throughout the code. 
can't we use different approach? for example, comparing object itself to validate whether its updated or not?

2023-12-05 13:57 UTC, JoshRyu requested changes
I have added few comments! please have a look at them!

2023-12-12 06:56 UTC, ZinnaChoi commented on backend/src/main/java/com/madeg/logistics/service/CategoryService.java
> +        patchInput.getParentCategoryCode()
I reuse the variable! thanks~

2023-12-12 06:57 UTC, ZinnaChoi commented on backend/src/main/java/com/madeg/logistics/service/StoreService.java
> +      isUpdated = true;
I use object change detection logic without using isUpdated flag
I changed for product, category and store!

check it and give me a feedback plz 😛

2023-12-12 13:18 UTC, JoshRyu approved these changes
Looks good!

2023-12-12 13:19 UTC, merged