Create APIs related to sales history & Refactor services to have common service
JoshRyu/logistics pull request #17
Opened 2023-12-26 13:56 UTC by ZinnaChoi

Hi, @JoshRyu 

I've developed several APIs concerning sales history. 

For retrieval purposes, there are two types I've created:
- An API to get a store's sales history by product.
- An API to get a store's sales history by month, specified by year and month.
If there's a need for other types of retrieval APIs, please don't hesitate to let me know.

Additionally, I've incorporated a CommonService to minimize code duplication!

I'd really appreciate your feedback on these developments! 😚

2023-12-26 14:38 UTC, JoshRyu requested changes
Please check out my comments!

2023-12-26 14:38 UTC, JoshRyu commented on backend/src/main/java/com/madeg/logistics/service/SalesHistoryService.java
> +      previousStoreProduct.getStockCnt() - salesHistoryInput.getQuantity()
Overall looks very good! always thanks for your contribution.
I reckon below code can make a outofstock result.

previousStoreProduct.getStockCnt() - salesHistoryInput.getQuantity()
- if salesHistoryInput.getQuantity() is greater than  > previousStoreProduct.getStockCnt(), it means the owner sold more products than it is currently stocked.

2023-12-26 14:38 UTC, JoshRyu commented on backend/src/main/java/com/madeg/logistics/service/SalesHistoryService.java
> +    if (storeProduct == null) {
I think this logic can be replaced by the CommonService's findStoreProduct method!

2023-12-26 14:38 UTC, JoshRyu commented on backend/src/main/java/com/madeg/logistics/service/SalesHistoryService.java
> +      previousStoreProduct.getStockCnt() - salesHistoryInput.getQuantity()
In addition to this,  I have checked our previous code related to "restock" and find out there is possible error.
The statement is followed as:
- if storeProduct is restocked 10 items while product has only 5 stocks, it does not prompt error.

2023-12-27 13:46 UTC, ZinnaChoi commented on backend/src/main/java/com/madeg/logistics/service/SalesHistoryService.java
> +      previousStoreProduct.getStockCnt() - salesHistoryInput.getQuantity()
I have added the constraints to product, store_product and sales_history!

2023-12-27 13:48 UTC, ZinnaChoi commented on backend/src/main/java/com/madeg/logistics/service/SalesHistoryService.java
> +    if (storeProduct == null) {
Actually, we usually find StoreProduct by both store and product, but in this case, we only need the store to get the store_product (it's only used once). If this logic is duplicated later, I think it would be better to move it.

2023-12-27 13:49 UTC, ZinnaChoi commented
Hi, @JoshRyu 

I fixed and refactor the logics!
Would you mind reviewing this?

2023-12-27 14:05 UTC, JoshRyu approved these changes
Looks great!

2023-12-27 14:05 UTC, merged